import React from 'react';
import { Check, X, CircleHelp, ArrowUpRight } from 'lucide-react';
export default function ValidationResult({ result }) {
  if (!result) return null;
  const valid = result.status === 'valid';
  const invalid = result.status === 'invalid';
  return <section aria-live="polite" className="mt-5 overflow-hidden rounded-2xl border border-[#dce1d5] bg-white text-left">
    <div className="flex items-start gap-3 p-5"><span className={valid ? 'rounded-full bg-[#c2f486] p-2' : invalid ? 'rounded-full bg-[#f8e2dc] p-2 text-[#a54132]' : 'rounded-full bg-[#f1ecd7] p-2 text-[#887330]'}>{valid ? <Check size={20} /> : invalid ? <X size={20} /> : <CircleHelp size={20} />}</span><div className="min-w-0"><h2 className="font-semibold">{valid ? 'Verified. It’s on-chain.' : invalid ? 'this is not valid get rekt' : 'Unable to verify'}</h2><p className="mt-1 text-xs leading-relaxed text-[#7c8275]">{valid ? 'Actual image bytes, stored on Solana and linked to this token.' : result.reason || result.message}</p></div></div>
    {valid && <><div className="proof-image flex justify-center border-y border-[#e5e8e0] p-6"><img src={result.image} alt="Verified image decoded directly from the token’s on-chain inscription" className="max-h-80 max-w-full rounded-lg object-contain" /></div><div className="space-y-3 p-5 text-xs"><div className="flex justify-between"><span className="text-[#878d7f]">Storage</span><span>Solana · {(result.bytes / 1024).toFixed(1)} KB · {result.mime.split('/')[1].toUpperCase()}</span></div><div className="flex justify-between"><span className="text-[#878d7f]">Update authority</span><span>{result.immutable ? 'Removed · immutable' : 'Active · image can change'}</span></div><div className="flex justify-between gap-3"><span className="text-[#878d7f]">Token mint</span><a href={`https://solscan.io/token/${result.mint}`} target="_blank" rel="noreferrer" className="flex items-center gap-1 font-mono text-[#58812d]">{result.mint.slice(0, 6)}…{result.mint.slice(-6)}<ArrowUpRight size={12} /></a></div><div className="flex justify-between"><span className="text-[#878d7f]">Image account</span><a href={`https://solscan.io/account/${result.imageAccount}`} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-[#58812d]">View on explorer<ArrowUpRight size={12} /></a></div><details className="border-t border-[#e5e8e0] pt-3"><summary className="cursor-pointer text-[#7c8275]">View verification details</summary><p className="mt-3 break-all font-mono text-[10px] leading-5 text-[#7c8275]">Standard: {result.standard}<br />Commitment: finalized<br />Metadata: {result.metadata}<br />SHA-256: {result.hash}<br />Checked: {result.checkedAt}</p></details><p className="text-[10px] leading-relaxed text-[#959b8e]">Verifies storage and token linkage at lookup time, not ownership, originality, token value, or safety.</p></div></>}
  </section>;
}